package jpad.configs.ex.enumerations;

public enum AeroConfigurationTypeEnum {
	
	UNKNOWN,
	EMPTY,
	FUSELAGE_ISOLATED,
	FUSELAGE_NACELLES_ISOLATED,
	WING_ISOLATED,
	WING_NACELLES_ISOLATED,
	WING_FUSELAGE,
	WING_FUSELAGE_NACELLES,
	WING_HTAIL,
	WING_NACELLES_HTAIL,
	WING_HTAIL_VTAIL,
	WING_NACELLES_HTAIL_VTAIL,
	WING_FUSELAGE_HTAIL,
	WING_FUSELAGE_HTAIL_NACELLES,
	WING_FUSELAGE_HTAIL_VTAIL,
	WING_FUSELAGE_HTAIL_VTAIL_NACELLES,
	WING_CANARD,
	WING_CANARD_HTAIL
	// add the rest ...
}
