package jpad.configs.ex.enumerations;

/**
 * Airplane type from Table 2.1 Roskam
 * @author Vittorio Trifari
 *
 */
public enum AirplaneType
{
	PISTON_HOMEBUILT,
	PISTON_SINGLE_ENGINE,
	PISTON_TWIN_ENGINE,
	PISTON_AGRICULTURAL,
	TURBOFAN_BUSINESS_JETS,
	TURBOPROP_REGIONAL,
	TURBOFAN_TRANSPORT_JETS,
	MILITARY_TRAINERS,
	MILITARY_FIGHTERS,
	MILITARY_PATROL_BOMB_TRANSPORT,
	FLYING_BOATS_AMPHIBIOUS_FLOATAIRPLANES,
	SUPERSONIC_CRUISE,
}
