package jpad.configs.ex.enumerations;

/**
 * The aircraft components that can be created by the application
 * to make up an aircraft
 *  
 * @author LA
 *
 */
public enum ComponentEnum{
	ALL,
	AIRCRAFT,
	UNDEFINED,
	WING,
	WING_AIRFOIL,
	HORIZONTAL_TAIL, 
	HORIZONTAL_TAIL_AIRFOIL,
	VERTICAL_TAIL,
	VERTICAL_TAIL_AIRFOIL,
	CANARD,
	CANARD_AIRFOIL,
	FUSELAGE,
	NACELLE,
	LANDING_GEAR,
	POWER_PLANT,
	FUEL_TANK,
	SYSTEMS, 
	APU,
	AIR_CONDITIONING_AND_ANTI_ICING,
	INSTRUMENTS_AND_NAVIGATION,
	FURNISHINGS_AND_EQUIPMENTS,
	HYDRAULIC_AND_PNEUMATICS,
	ELECTRICAL_SYSTEMS,
	CONTROL_SURFACES,
	ENGINE,
	CABIN_CONFIGURATION,
	WINGBODY;
}