package jpad.configs.ex.enumerations;

public enum FuselageAdjustCriteriaEnum {

	ADJ_TOT_LENGTH_CONST_LENGTH_RATIOS_DIAMETERS,
	ADJ_TOT_LENGTH_CONST_FINENESS_RATIOS,	
	ADJ_CYL_LENGTH,                                          // stretching
	ADJ_NOSE_LENGTH_CONST_TOT_LENGTH_DIAMETERS,
	ADJ_NOSE_LENGTH_CONST_LENGTH_RATIOS_DIAMETERS,
	ADJ_NOSE_LENGTH_CONST_FINENESS_RATIOS_VAR_LENGTHS,
	ADJ_TAILCONE_LENGTH_CONST_TOT_LENGTH_DIAMETERS,
	ADJ_TAILCONE_LENGTH_CONST_LENGTH_RATIOS_DIAMETERS,
	ADJ_TAILCONE_LENGTH_CONST_FINENESS_RATIOS_VAR_LENGTHS,
	ADJ_FUS_LENGTH_CONST_FINENESS_RATIOS_VAR_DIAMETERS
	
}
